const media = [
    {
        id: 1,
        type: "movie",
        title: "The Maze Runner",
		season: "S1",
		genre: "Action, Sci-Fi",
        actor: "Dylan O’Brien, Kaya Scodelario, Thomas Brodie-Sangster",
        country: "Amerika Serikat",
        year: 2014,
        rating: 6.8,
        poster: "https://i.pinimg.com/736x/dd/5e/f2/dd5ef2a4158d9c003052e0866086a011.jpg",
       	banner: "https://i1-c.pinimg.com/1200x/0c/69/1d/0c691dcfe8b8487e00f1af7ce0be568b.jpg",
		trailer: "https://youtu.be/AwwbhhjQ9Xk?si=I957yuY7OCE46-LT",
        featured: true,
        latest: false,
        description: "Sekelompok remaja terjebak di labirin berbahaya dan berusaha mencari jalan keluar."
    },

    {
        id: 2,
        type: "movie",
        title: "The Last 10 Years",
		genre: "Romance, Drama",
        actor: "Nana Komatsu, Kentaro Sakaguchi",
        country: "Jepang",
        year: 2022,
        rating: 7.0,
        poster: "https://i.pinimg.com/736x/eb/a4/b1/eba4b1dfcbdc56924f802e2a4d3e5ea0.jpg",
        trailer: "https://youtu.be/GyMXxOdHF7o?si=emweWc8BT3qvRodD",
        featured: false,
        latest: true,
        description: "Film ini menceritakan tentang seorang wanita muda yang didiagnosis mengidap penyakit langka dan diperkirakan hanya memiliki sisa hidup sekitar 10 tahun. Ia memilih menjauh dari cinta, namun hidupnya berubah setelah bertemu seorang pria yang membuatnya kembali merasakan kebahagiaan."
    },
	{
        id: 3,
        type: "movie",
        title: "Love Letter ",
		genre: "Romance, Drama",
        actor: "Miho Nakayama, Etsushi Toyokawa, Takashi Kashiwabara",
        country: "Jepang",
        year: 1995,
        rating: 7.9,
        poster: "https://i.pinimg.com/1200x/c3/c1/1f/c3c11ffdef92c94fc4331f0d1ff209d0.jpg",
        trailer: "https://youtu.be/P6JAtpSC0EA?si=xHe79PbZ1D-Qg3-K",
        featured: false,
        latest: true,
        description: "Seorang wanita mengirim surat ke alamat lama tunangannya yang telah meninggal, namun secara tak terduga mendapat balasan dari seseorang dengan nama yang sama. Dari situ, kenangan masa lalu dan kisah cinta perlahan terungkap."
    },
	{
        id: 4,
        type: "movie",
        title: "Grave of the Fireflies",
		genre: "Animation, Drama, War",
        actor: "Tsutomu Tatsumi, Ayano Shiraishi (Pengisi Suara)",
        country: "Jepang",
        year: 1998,
        rating: 8.5,
        poster: "https://i.pinimg.com/736x/b8/84/b2/b884b2f5f9fd4a9be8b4d53ac9552aef.jpg",
        trailer: "https://youtu.be/lhlh7JVcTt8?si=EOSD4BUCKejq9GSJ",
        featured: false,
        latest: true,
        description: "Di tengah kehancuran Jepang saat Perang Dunia II, dua saudara harus bertahan hidup sendirian setelah kehilangan keluarga mereka. Dengan keterbatasan makanan dan tempat tinggal, mereka berjuang melawan kerasnya realita perang, menghadirkan kisah yang sederhana namun sangat menyayat hati."
    },
	{
        id: 5,
        type: "series",
        title: "Touch Your Heart",
		genre: "Romance, Comedy, Drama",
        actor: "Lee Dong-wook, Yoo In-na",
        country: "Korea Selatan",
        year: 2019,
        rating: 7.6,
        poster: "https://i.pinimg.com/736x/1d/17/b1/1d17b10db666f76e3545eff62988a07b.jpg",
        trailer: "https://youtu.be/7Sdq9d3aN3g?si=evT7mEAhPVCcx5Zg",
        featured: false,
        latest: true,
        description: "Seorang aktris terkenal yang kariernya meredup harus bekerja sebagai sekretaris di sebuah firma hukum untuk mendalami peran barunya. Di sana ia dipasangkan dengan pengacara dingin dan perfeksionis. Awalnya sering bertabrakan, keduanya perlahan saling mengenal dan tumbuh kedekatan yang manis di tengah dunia kerja yang penuh tekanan."
    },
	{
        id: 6,
        type: "series",
        title: "100 Days My Prince",
		genre: "Romance, Historical, Comedy",
        actor: "D.O. (Do Kyung-soo), Nam Ji-hyun",
        country: "Korea Selatan",
        year: 2018,
        rating: 8.2,
        poster: "https://i.pinimg.com/736x/40/28/96/40289674801575e92b8804870c16cb5e.jpg",
        trailer: "https://youtu.be/X_Vz4q06vK8?si=dv9gciGsXv9rf_LT",
        featured: false,
        latest: true,
        description: "Seorang pangeran yang kehilangan ingatannya setelah insiden berbahaya hidup sebagai rakyat biasa selama 100 hari. Di kehidupannya yang baru, ia bertemu seorang wanita cerdas yang hidup sederhana namun penuh tantangan. Perlahan, hubungan mereka berkembang di tengah rahasia masa lalu yang mulai terungkap."
    },
	{
        id: 7,
        type: "series",
        title: "Youth of May",
		genre: "Romance, Drama, Historical",
        actor: "Lee Do-hyun, Go Min-si",
        country: "Korea Selatan",
        year: 2021,
        rating: 8.6,
        poster: "https://i.pinimg.com/1200x/36/3f/74/363f74ffe3d9ce2d7a1775c9877776c0.jpg",
        trailer: "https://youtu.be/NZPOPMnmBPw?si=2NUtiItrRslLJ7l2",
        featured: false,
        latest: true,
        description: "Berlatar masa gejolak politik di Korea tahun 1980, seorang mahasiswa kedokteran dan seorang perawat saling bertemu dan jatuh cinta di tengah situasi yang penuh ketegangan. Namun, hubungan mereka harus diuji oleh kenyataan pahit yang terjadi di sekitar mereka, membuat kisah cinta ini hangat sekaligus tragis."
    },
	{
        id: 8,
        type: "series",
        title: "D.P.",
		season: "S1",
		genre: "Action, Drama, Crime",
        actor: "Jung Hae-in, Koo Kyo-hwan, Kim Sung-kyun",
        country: "Korea Selatan",
        year: 2021,
        rating: 8.2,
        poster: "https://i.pinimg.com/1200x/00/a4/da/00a4da90194b9bf0022df6e65d141e08.jpg",
        banner: "https://i1-c.pinimg.com/736x/f0/02/73/f0027321b9884b1d9af4bd943d3826d8.jpg",
		trailer: "https://youtu.be/ru0PmaWoHxM?si=-zgFaEmb-H6YRLyn",
        featured: false,
        latest: true,
        description: "Seorang tentara muda ditugaskan dalam unit khusus yang bertugas menangkap tentara yang melarikan diri dari wajib militer. Dalam setiap misi, ia menemukan berbagai kisah kelam dan alasan menyakitkan di balik para deserter, yang membuatnya mulai mempertanyakan sistem militer itu sendiri."
    },
	{
        id: 9,
        type: "series",
        title: "Descendants of the Sun",
		genre: "Romance, Drama, Action",
        actor: "Song Joong-ki, Song Hye-kyo, Jin Goo, Kim Ji-won",
        country: "Korea Selatan",
        year: 2016,
        rating: 8.2,
        poster: "https://i.pinimg.com/736x/d2/f8/f3/d2f8f337141797e0f6c4a915251fe516.jpg",
        trailer: "https://youtu.be/wkHjOTFv60g?si=FmxTb_4vhvplAWrJ",
        featured: false,
        latest: true,
        description: "Seorang kapten pasukan khusus dan seorang dokter bertemu di tengah tugas masing-masing di zona konflik. Di antara misi berbahaya, bencana, dan situasi medis darurat, keduanya membangun hubungan yang kuat. Namun perbedaan pekerjaan dan kondisi ekstrem membuat cinta mereka terus diuji oleh risiko hidup dan mati."
    },
	{
        id: 10,
        type: "series",
        title: "Moon Lovers: Scarlet Heart Ryeo",
		genre: "Romance, Drama",
        actor: "Lee Joon-gi, IU, Kang Ha-neul, Nam Joo-hyuk",
        country: "Korea Selatan",
        year: 2016,
        rating: 8.6,
        poster: "https://i.pinimg.com/1200x/9c/98/f9/9c98f9a094e911e86868b24a487c2942.jpg",
        trailer: "https://youtu.be/2ljxyaAIphc?si=JwArP4HG97sjlFIi",
        featured: false,
        latest: true,
        description: "Seorang wanita dari masa modern tiba-tiba terlempar ke era dinasti Goryeo dan masuk ke tubuh seorang bangsawan muda. Di istana, ia terlibat dalam perebutan kekuasaan antar pangeran sekaligus hubungan rumit dengan mereka. Di tengah politik yang kejam dan konflik keluarga kerajaan, ia harus bertahan sambil menghadapi cinta dan pengkhianatan yang mengubah hidupnya."
    },
	{
        id: 11,
        type: "series",
        title: "Goblin (Guardian: The Lonely and Great God)",
		genre: "Romance, Drama",
        actor: "Gong Yoo, Kim Go-eun, Lee Dong-wook, Yoo In-na",
        country: "Korea Selatan",
        year: 2016,
        rating: 8.6,
        poster: "https://i.pinimg.com/1200x/66/cb/ab/66cbabb316ce82cbe98e5dff317d5b8d.jpg",
        trailer: "https://youtu.be/8AcNEVUzV4o?si=iMuxElfI5P8vZ3HR",
        featured: false,
        latest: true,
        description: "Seorang goblin abadi yang dikutuk untuk hidup selamanya mencari pengantin manusia yang bisa mencabut pedang tak terlihat di tubuhnya agar ia bisa mengakhiri hidupnya. Hidupnya berubah ketika ia bertemu seorang gadis ceria yang ternyata memiliki takdir istimewa. Di antara kehidupan, kematian, dan takdir, kisah mereka dipenuhi cinta, kesedihan, dan keajaiban."
    },
	{
        id: 12,
        type: "series",
        title: "W: Two Worlds",
		genre: "Romance, Thriller, Fantasy",
        actor: "Lee Jong-suk, Han Hyo-joo",
        country: "Korea Selatan",
        year: 2016,
        rating: 8.0,
        poster: "https://i.pinimg.com/736x/3e/a2/5e/3ea25e16875e5310c29fda940cd50151.jpg",
        trailer: "https://youtu.be/iFyxffHNwvE?si=zxXJ1T6P3yJ19whX",
        featured: false,
        latest: true,
        description: "Seorang dokter tanpa sengaja terseret ke dalam dunia webtoon yang dibuat oleh ayahnya. Di sana, ia bertemu karakter utama pria yang ternyata bisa keluar masuk antara dunia komik dan dunia nyata. Keduanya terjebak dalam alur cerita yang tidak stabil, di mana batas antara realita dan fiksi mulai kabur."
    },
	{
        id: 13,
        type: "series",
        title: "Fight for My Way",
		genre: "Romance, Comedy, Drama",
        actor: "Park Seo-joon, Kim Ji-won",
        country: "Korea Selatan",
        year: 2017,
        rating: 8.1,
        poster: "https://i.pinimg.com/736x/23/34/3f/23343feeddca9e997c1f8d5379fbdba9.jpg",
        trailer: "https://youtu.be/pIh-X7o1Y-U?si=uhyXQnqV0MiHdVBE",
        featured: false,
        latest: true,
        description: "Dua sahabat yang sudah lama mengenal satu sama lain berjuang mengejar mimpi mereka di tengah hidup yang serba terbatas. Meski sering gagal dan diremehkan, mereka tetap berusaha bertahan dan menemukan jalan hidup masing-masing, sambil perlahan menyadari perasaan yang tumbuh di antara mereka."
    },
	{
        id: 14,
        type: "series",
        title: "My ID is Gangnam Beauty",
		genre: "Romance, Drama",
        actor: "Im Soo-hyang, Cha Eun-woo",
        country: "Korea Selatan",
        year: 2018,
        rating: 7.3,
        poster: "https://i.pinimg.com/1200x/8b/51/e5/8b51e560aec4b3313e77db9a1304a8c2.jpg",
        trailer: "https://youtu.be/pBwTLwHzV8I?si=EsXVIhaSaDN-4Qb6",
        featured: false,
        latest: true,
        description: "Seorang gadis yang pernah merasa tidak percaya diri karena penampilannya menjalani operasi plastik agar hidupnya lebih baik. Namun saat masuk kuliah, ia justru masih menghadapi tekanan, komentar orang lain, dan standar kecantikan yang tidak adil. Di tengah proses menemukan jati diri, ia perlahan belajar mencintai dirinya sendiri dengan bantuan orang-orang yang tulus di sekitarnya."
    },
	{
        id: 15,
        type: "series",
        title: "Vagabond",
		genre: "Action, Thriller, Crime",
        actor: "Lee Seung-gi, Bae Suzy",
        country: "Korea Selatan",
        year: 2019,
        rating: 8.1,
        poster: "https://i.pinimg.com/736x/95/5d/f3/955df33b2cfc3c0e3834f0ac05963aab.jpg",
        trailer: "https://youtu.be/tyhnEHCUtv4?si=pvkpA4Q23RmsGlnG",
        featured: false,
        latest: true,
        description: "Seorang stuntman tanpa sengaja terlibat dalam kasus jatuhnya pesawat yang menewaskan banyak orang, termasuk keponakannya. Saat mencoba mengungkap kebenaran, ia menemukan konspirasi besar yang melibatkan korupsi tingkat tinggi. Bersama seorang agen rahasia, ia berjuang mengungkap dalang di balik tragedi tersebut meski nyawanya terus terancam."
    },
	{
        id: 16,
        type: "series",
        title: "The King: Eternal Monarch",
		genre: "Romance, Drama",
        actor: "Lee Min-ho, Kim Go-eun",
        country: "Korea Selatan",
        year: 2020,
        rating: 8.1,
        poster: "https://i.pinimg.com/1200x/d7/67/17/d76717de32973384ee82e3940b3c5c59.jpg",
        trailer: "https://youtu.be/jJwuFjmfjRY?si=DImFHjHJLh9gRP-I",
        featured: false,
        latest: true,
        description: "Seorang kaisar dari dunia paralel menemukan pintu menuju dunia modern dan bertemu seorang detektif wanita. Keduanya bekerja sama melintasi dua dunia yang berbeda untuk mengungkap misteri yang mengancam keseimbangan kedua alam tersebut, sambil menjalin hubungan yang rumit di tengah takdir yang saling terhubung."
    },
	{
        id: 17,
        type: "series",
        title: "Sweet Home",
		season: "S1",
		genre: "Thriller, Action",
        actor: "Song Kang, Lee Jin-wook, Lee Si-young, Go Min-si",
        country: "Korea Selatan",
        year: 2020,
        rating: 7.3,
        poster: "https://i.pinimg.com/1200x/cd/2a/2a/cd2a2a82f3a483214d2cb1315b69c801.jpg",
        trailer: "https://youtu.be/7rI56NmD33Y?si=zPnDPrfu_yemN75-",
        featured: false,
        latest: true,
        description: "Seorang remaja yang baru kehilangan keluarganya pindah ke sebuah apartemen tua, namun tiba-tiba manusia di dunia mulai berubah menjadi monster mengerikan. Bersama para penghuni lain, ia harus bertahan hidup di dalam gedung yang terisolasi sambil menghadapi ancaman monster dan sisi gelap manusia itu sendiri."
    },
	{
        id: 18,
        type: "series",
        title: "Sweet Home",
		season: "S2",
		genre: "Thriller, Action",
        actor: "Song Kang, Lee Jin-wook, Lee Si-young, Go Min-si",
        country: "Korea Selatan",
        year: 2023,
        rating: 7.0,
        poster: "https://i.pinimg.com/736x/1d/9b/0a/1d9b0a03037c10134920047f03843210.jpg",
        trailer: "https://youtu.be/3WJweFedauI?si=RXnIEQLQumutxgll",
        featured: false,
        latest: true,
        description: "Setelah keluar dari Green Home, para penyintas harus berjuang di dunia luar yang sudah semakin kacau karena wabah monster. Cha Hyun-su dibawa ke fasilitas militer untuk diteliti, sementara ancaman baru muncul dari manusia yang mulai kehilangan batas antara manusia dan monster."
    },
	{
        id: 19,
        type: "series",
        title: "Sweet Home",
		season: "S3",
		genre: "Thriller, Action",
        actor: "Song Kang, Lee Jin-wook, Lee Si-young, Go Min-si",
        country: "Korea Selatan",
        year: 2024,
        rating: 6.8,
        poster: "https://i.pinimg.com/736x/6e/d8/9c/6ed89cd03e44541289bf337b5cb25021.jpg",
        trailer: "https://youtu.be/vFg5YGAORhU?si=VEtDSlOlSo5S2bAq",
        featured: false,
        latest: true,
        description: "Kisah berlanjut di dunia yang semakin hancur, di mana manusia, monster, dan “evolved humans” mulai bertarung untuk bertahan hidup. Hyun-su dan yang lain harus menghadapi keputusan sulit tentang apa arti menjadi manusia."
    },
	{
        id: 20,
        type: "series",
        title: "Record of Youth",
		genre: "Romance, Drama",
        actor: "Park Bo-gum, Park So-dam, Byeon Woo-seok",
        country: "Korea Selatan",
        year: 2020,
        rating: 7.2,
        poster: "https://i.pinimg.com/736x/5b/eb/ca/5bebca800d1c9d8497e089b3ada3367f.jpg",
        trailer: "https://youtu.be/I6xYiGtsyDs?si=OXTmRloBPX_hqvqU",
        featured: false,
        latest: true,
        description: "Tiga anak muda dengan latar belakang berbeda berjuang mengejar impian di dunia hiburan dan fashion. Di tengah kerasnya industri dan tekanan hidup, mereka mencoba tetap bertahan sambil mencari arti sukses, cinta, dan kebahagiaan yang sebenarnya."
    },
	{
        id: 21,
        type: "series",
        title: "True Beauty",
		genre: "Romance, Comedy, Drama",
        actor: "Moon Ga-young, Cha Eun-woo, Hwang In-yeop",
        country: "Korea Selatan",
        year: 2020,
        rating: 8.0,
        poster: "https://i.pinimg.com/736x/00/ec/0b/00ec0b03efc08794fa3088ea3e8461a8.jpg",
        trailer: "https://youtu.be/BhP1eYQ5Pxk?si=g99Ngj7eift0uGZu",
        featured: false,
        latest: true,
        description: "Seorang gadis yang sering diremehkan karena penampilannya belajar makeup untuk mengubah dirinya di sekolah baru. Ia menjadi populer, tetapi terus hidup dengan rasa takut jika orang lain mengetahui wajah aslinya. Di tengah itu, ia terjebak dalam hubungan rumit dengan dua pria yang mulai menyukainya."
    },
	{
        id: 22,
        type: "series",
        title: "Vincenzo",
		genre: "Action, Comedy, Drama",
        actor: "Song Joong-ki, Jeon Yeo-been, Ok Taec-yeon",
        country: "Korea Selatan",
        year: 2021,
        rating: 8.4,
        poster: "https://i.pinimg.com/1200x/2b/47/e9/2b47e9eb32c09997506c786f87869fc5.jpg",
        trailer: "https://youtu.be/1b1-nK0HM9c?si=dqHyl37Qpz8QcmCv",
        featured: false,
        latest: true,
        description: "Seorang pengacara mafia yang dibesarkan di Italia kembali ke Korea untuk mengambil emas tersembunyi di sebuah gedung. Namun, ia justru terlibat konflik dengan perusahaan korup yang sangat kuat. Dengan cara yang licik dan brutal, ia bersama seorang pengacara lokal melawan para penjahat menggunakan strategi hukum dan dunia kriminal."
    },
	{
        id: 23,
        type: "series",
        title: "Hometown Cha-Cha-Cha",
		genre: "Romance, Comedy, Drama",
        actor: "Shin Min-a, Kim Seon-ho, Lee Sang-yi",
        country: "Korea Selatan",
        year: 2021,
        rating: 8.4,
        poster: "https://i.pinimg.com/1200x/43/0d/55/430d55b69f3d811c8be77c8f8031bc3e.jpg",
        trailer: "https://youtu.be/VOgD00LFsMI?si=NrDKv0ZpMQIPc4hy",
        featured: false,
        latest: true,
        description: "Seorang dokter gigi dari kota besar pindah ke desa tepi laut dan bertemu pria serba bisa yang sangat membantu warga sekitar. Di tengah kehidupan desa yang hangat dan sederhana, keduanya perlahan saling mengenal dan tumbuh kedekatan yang membawa perubahan dalam hidup mereka."
    },
	{
        id: 24,
        type: "series",
        title: "Doom at Your Service",
		genre: "Romance, Drama",
        actor: "Park Bo-young, Seo In-guk",
        country: "Korea Selatan",
        year: 2021,
        rating: 7.8,
        poster: "https://i.pinimg.com/1200x/75/73/48/757348ac1603acc247a4dc2ac4fe1b11.jpg",
        trailer: "https://youtu.be/_V5w-SG8ERs?si=HRtejc89TGMS-EpN",
        featured: false,
        latest: true,
        description: "Seorang wanita yang hidupnya penuh kesulitan secara tidak sengaja memanggil makhluk misterius yang bisa menghancurkan dunia. Ia kemudian membuat perjanjian dengannya, dan selama 100 hari hidupnya berubah drastis. Di tengah waktu yang terbatas, keduanya perlahan membangun hubungan yang hangat namun penuh dilema antara cinta, takdir, dan kematian."
    },
	{
        id: 25,
        type: "series",
        title: "My Name",
		genre: "Action, Thriller, Crime",
        actor: "Han So-hee, Park Hee-soon, Ahn Bo-hyun",
        country: "Korea Selatan",
        year: 2021,
        rating: 7.8,
        poster: "https://i.pinimg.com/736x/57/6e/af/576eaf5037d6fb1ec495ebb4ce8555e2.jpg",
        trailer: "https://youtu.be/d2h92UnKr6s?si=walQWkqzjKypcEzo",
        featured: false,
        latest: true,
        description: "Seorang gadis muda menyamar dengan identitas baru setelah kematian ayahnya yang misterius. Ia masuk ke dunia kriminal dan bergabung dengan organisasi berbahaya untuk mengungkap kebenaran serta membalas dendam. Dalam prosesnya, ia harus hidup di antara dua dunia: kepolisian dan mafia, sambil menyembunyikan identitas aslinya."
    },
	 {
        id: 26,
        type: "series",
        title: "D.P.",
		season: "S2",
		genre: "Action, Drama, Crime",
        actor: "Jung Hae-in, Koo Kyo-hwan, Kim Sung-kyun",
        country: "Korea Selatan",
        year: 2023,
        rating: 8.3,
        poster: "https://i.pinimg.com/736x/dd/77/d1/dd77d177ce6b23576c9e82ddac86f1bd.jpg",
        trailer: "https://youtu.be/SxnY2E_uMtY?si=LcPCMJAtAYTgX2ze",
        featured: true,
        latest: false,
        description: "Setelah berbagai kasus di season sebelumnya, unit D.P. kembali menghadapi kejadian yang lebih rumit dan gelap. Mereka semakin terjebak dalam konflik internal militer dan tekanan sistem yang keras, sambil terus mengejar para desertir yang memiliki cerita tragis masing-masing."
    },
	{
        id: 29,
        type: "series",
        title: "Lovestruck in the City",
		genre: "Romance, Drama",
        actor: "Ji Chang-wook, Kim Ji-won, Kim Min-seok, Han Ji-eun",
        country: "Korea Selatan",
        year: 2020,
        rating: 7.6,
        poster: "https://i.pinimg.com/736x/30/8e/9d/308e9d5049693f123749d5c614ccbefe.jpg",
        trailer: "https://youtu.be/c_LSBRJB3wE?si=HSct5QeeuDO14RdK",
        featured: true,
        latest: false,
        description: "Kisah cinta beberapa orang muda di Seoul yang penuh lika-liku dan realita kehidupan. Seorang arsitek yang masih belum bisa melupakan cinta lamanya menceritakan kembali hubungan mereka yang rumit, manis, dan menyakitkan di tengah kehidupan kota yang sibuk dan penuh tekanan."
    },
	{
        id: 30,
        type: "series",
        title: "Sisyphus: The Myth",
		genre: "Sci-Fi, Action, Mystery, Drama",
        actor: "Cho Seung-woo, Park Shin-hyen",
        country: "Korea Selatan",
        year: 2021,
        rating: 7.0,
        poster: "https://i.pinimg.com/1200x/f2/11/27/f21127de9f5676f79f1165aff49ba18d.jpg",
        trailer: "https://youtu.be/-qMlwHnQmGM?si=vqso_mKydrciPc5Z",
        featured: true,
        latest: false,
        description: "Seorang insinyur jenius tanpa sengaja menemukan rahasia besar tentang perjalanan waktu dan organisasi misterius yang mengendalikan masa depan. Ia bertemu seorang wanita dari masa depan yang datang untuk menyelamatkannya, dan bersama-sama mereka berusaha mengubah nasib dunia yang penuh bahaya dan paradoks waktu."
    },
	{
        id: 31,
        type: "series",
        title: "Business Proposal",
		genre: "Romance, Comedy",
        actor: "Ahn Hyo-seop, Kim Se-jeong, Kim Min-kyu, Seol In-ah",
        country: "Korea Selatan",
        year: 2022,
        rating: 8.1,
        poster: "https://i.pinimg.com/736x/ac/17/cc/ac17ccc9899b0ccc56ccbcac1876d52d.jpg",
        trailer: "https://youtu.be/mh4R-WXRhQo?si=0mDOaeNNJeo7r3rW",
        featured: true,
        latest: false,
        description: "Seorang wanita pergi ke kencan buta menggantikan temannya, tanpa tahu bahwa pria yang ia temui adalah CEO perusahaan tempat ia bekerja. Untuk menyembunyikan identitasnya, ia berpura-pura menjadi orang lain, namun situasi semakin rumit ketika sang CEO justru menaruh hati padanya."
    },
	{
        id: 32,
        type: "series",
        title: "Twenty-Five Twenty-One",
		genre: "Romance, Drama, Sport",
        actor: "Kim Tae-ri, Nam Joo-hyuk, Bona, Choi Hyun-wook",
        country: "Korea Selatan",
        year: 2022,
        rating: 8.6,
        poster: "https://i.pinimg.com/736x/fc/38/94/fc38942d9ac17ddce4c6abadcf13b104.jpg",
        trailer: "https://youtu.be/n7F8o-SoK8s?si=QK0aI_H6cK42hzjt",
        featured: true,
        latest: false,
        description: "Berlatar krisis ekonomi akhir 1990-an, seorang atlet anggar muda berjuang mengejar impiannya di tengah masa sulit. Ia bertemu seorang pemuda yang juga sedang mencari arah hidupnya. Bersama, mereka saling mendukung, tumbuh, dan mengalami kisah persahabatan sekaligus cinta yang hangat namun penuh makna."
    },
	{
        id: 33,
        type: "series",
        title: "All of Us Are Dead",
		genre: "Thriller, Action, Drama",
        actor: "Yoon Chan-young, Park Ji-hu, Cho Yi-hyun, Lomon",
        country: "Korea Selatan",
        year: 2022,
        rating: 7.5,
        poster: "https://i.pinimg.com/736x/30/c6/c3/30c6c3d4e8af5488f2892deed6132829.jpg",
        trailer: "https://youtu.be/xVN-y9OaSag?si=03NjjnCFD8Hs9tR2",
        featured: true,
        latest: false,
        description: "Sebuah wabah zombie tiba-tiba menyebar di sebuah sekolah, membuat para siswa terjebak tanpa jalan keluar. Mereka harus bertahan hidup di tengah kekacauan, melawan zombie dan konflik antar manusia, sambil mencari cara untuk keluar dari situasi mematikan tersebut."
    },
	{
        id: 34,
        type: "movie",
        title: "The Wind Rises (Kaze Tachinu)",
		genre: "Animation, Drama, Romance, Historical",
        actor: "Hideaki Anno, Miori Takimoto (Pengisi Suara)",
        country: "Jepang",
        year: 2013,
        rating: 7.8,
        poster: "https://i.pinimg.com/1200x/67/ef/7c/67ef7c65f2c9a0514ce892d568553b3a.jpg",
        trailer: "https://youtu.be/RzSpDgiF5y8?si=O13o6s5PLSX5mXhy",
        featured: true,
        latest: false,
        description: "Kisah seorang insinyur pesawat jenius Jepang yang bercita-cita menciptakan pesawat terbang indah di tengah masa perang. Di balik mimpinya, ia juga menjalani kisah cinta yang menyentuh dengan seorang wanita yang sedang sakit. Film ini menggambarkan mimpi, cinta, dan realita perang yang saling bertabrakan."
    },
	{
        id: 35,
        type: "series",
        title: "Attack on Titan",
		season: "S1",
		genre: "Animation, Action, Fantasy, Drama, Dark Fantasy",
        actor: "Hideaki Anno, Miori Takimoto (Pengisi Suara)",
        country: "Jepang",
        year: 2013,
        rating: 8.5,
        poster: "https://i.pinimg.com/1200x/44/9a/80/449a800a063afedaf60acf71078d9567.jpg",
        trailer: "https://youtu.be/c44sr5cw-DY?si=5RSx6Br6dJsL24qo",
        featured: true,
        latest: false,
        description: "Eren Yeager hidup di dunia yang dikelilingi tembok raksasa untuk melindungi manusia dari Titan. Namun ketika Titan kolosal dan armored menyerang, hidupnya berubah total. Bersama Mikasa dan Armin, ia bergabung dengan militer untuk melawan Titan dan mencari kebenaran di balik dunia yang mereka tinggali."
    },
	{
        id: 36,
        type: "series",
        title: "Attack on Titan",
		season: "S2",
		genre: "Animation, Action, Fantasy, Drama, Dark Fantasy",
        actor: "Hideaki Anno, Miori Takimoto (Pengisi Suara)",
        country: "Jepang",
        year: 2017,
        rating: 8.6,
        poster: "https://i.pinimg.com/1200x/91/d9/b4/91d9b462a03c73ea3bf6083ec4dafecb.jpg",
        trailer: "https://youtu.be/M7qnG3W_LOw?si=vjl1G6TtJ8HrDcSH",
        featured: true,
        latest: false,
        description: "Ancaman Titan semakin dekat dan mengejutkan ketika muncul Titan yang bisa berpikir seperti manusia. Di tengah pertempuran, terungkap bahwa musuh sebenarnya tidak hanya di luar tembok, tetapi juga sudah ada di antara mereka sendiri."
    },
	{
        id: 37,
        type: "series",
        title: "Attack on Titan",
		season: "S3",
		genre: "Animation, Action, Fantasy, Drama, Dark Fantasy",
        actor: "Hideaki Anno, Miori Takimoto (Pengisi Suara)",
        country: "Jepang",
        year: 2018,
        rating: 9.0,
        poster: "https://i.pinimg.com/736x/c6/0b/60/c60b60375d1cdb2f35edf8f2d4b78d92.jpg",
        trailer: "https://youtu.be/nEzpVFCZ3HE?si=-wUGcklOqarGuRsd",
        featured: true,
        latest: false,
        description: "Pertarungan berubah menjadi konflik antar manusia, bukan hanya Titan. Pemerintah dan rahasia kerajaan mulai terbongkar, mengungkap sejarah kelam dunia yang selama ini disembunyikan dari semua orang."
    },
	{
        id: 38,
        type: "series",
        title: "Attack on Titan",
		season: "S4",
		genre: "Animation, Action, Fantasy, Drama, Dark Fantasy",
        actor: "Hideaki Anno, Miori Takimoto (Pengisi Suara)",
        country: "Jepang",
        year: 2020,
        rating: 9.1,
        poster: "https://i.pinimg.com/1200x/57/9a/e5/579ae58b014c6768cd7e32b678fa2a3d.jpg",
        trailer: "https://youtu.be/M_OauHnAFc8?si=WQ7NKw1NbReR9DNw",
        featured: true,
        latest: false,
        description: "Perang besar antara Marley dan Eldia pecah, membawa konflik ke skala dunia. Eren mengambil keputusan ekstrem yang mengguncang semua pihak, memaksa setiap karakter menghadapi pilihan sulit antara kebebasan, kemanusiaan, dan kehancuran."
    },
	{
        id: 39,
        type: "movie",
        title: "Your Eyes Tell",
		genre: "Romance, Drama",
        actor: "Hideaki Anno, Miori Takimoto",
        country: "Jepang",
        year: 2020,
        rating: 7.8,
        poster: "https://i.pinimg.com/1200x/60/d5/14/60d5142aff5c6814987b4ab29e2cc507.jpg",
        trailer: "https://youtu.be/OVkB5bB12ks?si=6l8fV0JSkK-NDSMJ",
        featured: true,
        latest: false,
        description: "Seorang pria mantan petinju yang hidupnya penuh penyesalan bertemu dengan seorang wanita yang kehilangan penglihatannya akibat kecelakaan. Di tengah kehidupan yang penuh luka, keduanya perlahan saling menyembuhkan dan menemukan kembali arti harapan, meski masa lalu mereka tidak mudah untuk dilupakan."
    },
	{
        id: 40,
        type: "series",
        title: "Alice in Borderland",
		season: "S1",
		genre: "Thriller, Survival, Sci-Fi",
        actor: "Kento Yamazaki, Tao Tsuchiya, Nijiro Murakami",
        country: "Jepang",
        year: 2020,
        rating: 7.7,
        poster: "https://i.pinimg.com/1200x/22/9d/a9/229da944a0c865f1a5a1602ed66aa34c.jpg",
        trailer: "https://youtu.be/49_44FFKZ1M?si=OKr3hDcbMJTNgxDv",
        featured: true,
        latest: false,
        description: "Arisu dan teman-temannya tiba-tiba terjebak di Tokyo kosong dan dipaksa ikut berbagai “game” mematikan untuk bertahan hidup. Mereka mulai memahami aturan dunia misterius ini sambil berusaha tetap hidup dan mencari jalan keluar."
    },
	{
        id: 41,
        type: "series",
        title: "Alice in Borderland",
		season: "S2",
		genre: "Thriller, Survival, Sci-Fi",
        actor: "Kento Yamazaki, Tao Tsuchiya, Nijiro Murakami",
        country: "Jepang",
        year: 2022,
        rating: 8.0,
        poster: "https://i.pinimg.com/1200x/c4/3e/f8/c43ef8c1c17cdcce3356390c8b5b9509.jpg",
        trailer: "https://youtu.be/1ifgEQCevYc?si=dQEKn4aQVROJgRTO",
        featured: true,
        latest: false,
        description: "Game semakin sulit dan berbahaya dengan munculnya “face cards” yang sangat kuat. Arisu dan kelompoknya harus menghadapi tantangan ekstrem sambil mencoba mengungkap siapa pengendali dunia Borderland sebenarnya."
    },
	{
        id: 42,
        type: "series",
        title: "Alice in Borderland",
		season: "S3",
		genre: "Thriller, Survival, Sci-Fi",
        actor: "Kento Yamazaki, Tao Tsuchiya, Nijiro Murakami",
        country: "Jepang",
        year: 2025,
        rating: 8.0,
        poster: "https://i.pinimg.com/736x/8a/48/3a/8a483a51293047e0088235749c4c3a55.jpg",
        trailer: "https://youtu.be/_8p6YkEPVco?si=5AlZ_SH1IA9E1QAZ",
        featured: true,
        latest: false,
        description: "Setelah hidup kembali di dunia nyata, Arisu mulai merasakan ada sesuatu yang “tidak beres”. Perlahan, tanda-tanda Borderland muncul lagi dan beberapa orang mulai terhubung kembali dengan dunia itu. Season ini fokus ke misteri baru tentang apa sebenarnya Borderland dan apakah itu benar-benar selesai atau hanya siklus yang berulang."
    },
	{
        id: 43,
        type: "series",
        title: "Jujutsu Kaisen",
		season: "S1",
		genre: "Animation, Action, Fantasy, Supernatural",
        actor: "Junya Enoki, Yuichi Nakamura, Asami SetoMurakami (Pengisi Suara)",
        country: "Jepang",
        year: 2020,
        rating: 8.5,
        poster: "https://i.pinimg.com/1200x/d9/bd/ca/d9bdca5ed0031f7203bac7af4a457081.jpg",
        trailer: "https://youtu.be/pkKu9hLT-t8?si=MBkzYjy1gUG1xBZ8",
        featured: true,
        latest: false,
        description: "Yuji Itadori terlibat dunia kutukan setelah menelan jari Sukuna, kutukan paling berbahaya. Ia bergabung dengan sekolah jujutsu untuk belajar mengendalikan kekuatan dan melawan kutukan yang mengancam manusia."
    },
	{
        id: 44,
        type: "series",
        title: "Jujutsu Kaisen",
		season: "S2",
		genre: "Animation, Action, Fantasy, Supernatural",
        actor: "Junya Enoki, Yuichi Nakamura, Asami SetoMurakami (Pengisi Suara)",
        country: "Jepang",
        year: 2023,
        rating: 8.7,
        poster: "https://i.pinimg.com/736x/9b/a0/64/9ba0646f348b9f86e1e188fed0a5de4b.jpg",
        trailer: "https://youtu.be/Pm-wNmS9RGI?si=s7hqrgf3EGkBTEKy",
        featured: true,
        latest: false,
        description: "Menceritakan masa lalu Gojo Satoru dan Geto Suguru, serta peristiwa besar yang mengubah dunia jujutsu. Season ini berlanjut ke insiden besar yang mengguncang para penyihir dan membuka konflik yang lebih gelap dan serius."
    },
	{
        id: 45,
        type: "movie",
        title: "Jujutsu Kaisen 0",
		genre: "Animation, Action, Fantasy, Supernatural",
        actor: "Megumi Ogata, Kana Hanazawa, Yuichi Nakamura (Pengisi Suara)",
        country: "Jepang",
        year: 2021,
        rating: 7.8,
        poster: "https://i.pinimg.com/1200x/9c/c1/9f/9cc19f8362628735f5188ddc1c4618e3.jpg",
        trailer: "https://youtu.be/UPRqnFnnrr8?si=5vKOYhUWT6Hpbs0q",
        featured: true,
        latest: false,
        description: "Film ini menceritakan Yuta Okkotsu, seorang siswa yang dihantui oleh roh kutukan dari teman masa kecilnya yang telah meninggal. Ia kemudian bergabung dengan sekolah jujutsu untuk belajar mengendalikan kekuatan tersebut. Di sana, ia menghadapi ancaman besar dari penyihir kuat yang ingin memanfaatkan kekuatannya."
    },
	{
        id: 46,
        type: "movie",
        title: "Even If This Love Disappears from the World Tonight",
		genre: "Romance, Drama",
        actor: "Shunsuke Michieda, Riko Fukumoto",
        country: "Jepang",
        year: 2022,
        rating: 7.5,
        poster: "https://i.pinimg.com/736x/c5/9d/fc/c59dfc8cabe8448b39839603316ef919.jpg",
        trailer: "https://youtu.be/Z-xXhqa6igU?si=Q7Ryytp65WEzw4wm",
        featured: true,
        latest: false,
        description: "Seorang gadis yang kehilangan ingatannya setiap kali tidur menjalani hidup dengan mencatat semua hal penting di buku harian. Ia kemudian bertemu seorang pria yang perlahan menjadi bagian penting dalam hidupnya. Di tengah keterbatasan ingatan, mereka berusaha mempertahankan perasaan yang terus terancam hilang setiap hari."
    },
	{
        id: 47,
        type: "movie",
        title: "The 355",
		genre: "Action, Thriller",
        actor: "Jessica Chastain, Lupita Nyong’o, Penélope Cruz, Diane Kruger, Fan Bingbing",
        country: "Amerika Serikat",
        year: 2022,
        rating: 5.6,
        poster: "https://i.pinimg.com/736x/73/76/69/7376699470dad51541024b097afc95cd.jpg",
        trailer: "https://youtu.be/DB20NfOp68k?si=IB3i6HQXDyXwJj1q",
        featured: true,
        latest: false,
        description: "Sekelompok agen wanita dari berbagai negara bekerja sama untuk menghentikan senjata berbahaya yang bisa mengancam dunia. Dengan kemampuan dan latar belakang berbeda, mereka harus menghadapi musuh kuat sambil saling belajar untuk percaya satu sama lain dalam misi yang penuh aksi dan risiko tinggi."
    },
	{
        id: 48,
        type: "series",
        title: "Hidden Love",
		genre: "Romance, Drama",
        actor: "Zhao Lusi, Chen Zheyuan",
        country: "China",
        year: 2023,
        rating: 8.6,
        poster: "https://i.pinimg.com/736x/09/c7/66/09c766f8803aa75cc841631580f7bea0.jpg",
        trailer: "https://youtu.be/tiwcMjH1dRw?si=YrxF-Au2_BkPslQt",
        featured: true,
        latest: false,
        description: "Seorang gadis diam-diam menyukai kakak dari sahabatnya sejak kecil. Setelah bertahun-tahun, mereka bertemu kembali dalam keadaan yang berbeda, dan perasaan lama yang tersembunyi perlahan tumbuh menjadi cinta yang nyata dan manis."
    },
	{
        id: 49,
        type: "movie",
        title: "Kung Fu Hustle",
		genre: "Action, Comedy, Fantasy",
        actor: "Stephen Chow, Yuen Wah, Yuen Qiu",
        country: "Hong Kong",
        year: 2004,
        rating: 7.7,
        poster: "https://i.pinimg.com/736x/e8/be/6a/e8be6af5512c2eaeeec86db2bb157204.jpg",
        trailer: "https://youtu.be/FtE9-o6dBEI?si=ymckBRtYgK4LvKtd",
        featured: true,
        latest: false,
        description: "Seorang pria kecil yang bercita-cita menjadi penjahat besar tanpa sengaja terlibat dalam konflik antara geng berbahaya dan para ahli kung fu tersembunyi. Dengan gaya unik yang penuh aksi dan komedi, film ini menghadirkan pertarungan seru sekaligus menghibur."
    },
	{
        id: 50,
        type: "movie",
        title: "Man in Love",
		genre: "Romance, Drama",
        actor: "Huang Cheng-yi, Ann Hsu",
        country: "Taiwan",
        year: 2021,
        rating: 7.0,
        poster: "https://i.pinimg.com/1200x/9b/07/93/9b0793f5232e71eefa13bcaf6bd64350.jpg",
        trailer: "https://youtu.be/udr78TOy-Kg?si=Gnc9IZ_RWu60k5xN",
        featured: true,
        latest: false,
        description: "Seorang penagih utang yang dikenal kasar dan hidup di dunia keras tiba-tiba jatuh cinta pada seorang wanita yang sederhana. Seiring waktu, ia berusaha berubah menjadi pribadi yang lebih baik, namun kenyataan hidup da"
    },
	{
        id: 51,
        type: "series",
        title: "The First Frost",
		genre: "Romance, Drama",
        actor: "Bai Jingting, Zhang Ruonan",
        country: "China",
        year: 2025,
        rating: 8.0,
        poster: "https://i.pinimg.com/736x/5a/5f/81/5a5f81fa49a6010020ae808f2d4c612a.jpg",
        trailer: "https://youtu.be/0hacR9QBkTU?si=w06rEj1HOYOSHaUV",
        featured: true,
        latest: false,
        description: "Mengisahkan Sang Yan, kakak dari sahabat tokoh utama di Hidden Love. Cerita berfokus pada kehidupan dan kisah cintanya yang lebih dewasa, penuh penyesalan, dan perasaan yang tidak tersampaikan. Dibandingkan Hidden Love, drama ini memiliki suasana yang lebih tenang, realistis, dan emosional."
    },
	{
        id: 52,
        type: "movie",
        title: "A Taxi Driver",
		genre: "Historical, Drama",
        actor: "Song Kang-ho, Thomas Kretschmann, Yoo Hae-jin, Ryu Jun-yeol",
        country: "Korea Selatan",
        year: 2017,
        rating: 7.9,
        poster: "https://i.pinimg.com/736x/05/81/71/0581713e3588c983e6daa793361d4ce7.jpg",
        trailer: "https://youtu.be/bB7z4Xn5oNA?si=yicXqIt_Op_uYGsD",
        featured: true,
        latest: false,
        description: "Seorang sopir taksi secara tidak sengaja mengantar jurnalis asing ke kota Gwangju saat terjadi demonstrasi besar. Tanpa disadari, ia terlibat dalam peristiwa bersejarah yang berbahaya, dan perlahan menyadari kenyataan pahit yang dialami rakyat di tengah situasi politik yang kacau."
    },
	{
        id: 53,
        type: "movie",
        title: "Train to Busan",
		genre: "Thriller, Action",
        actor: "Gong Yoo, Jung Yu-mi, Ma Dong-seok",
        country: "Korea Selatan",
        year: 2016,
        rating: 7.6,
        poster: "https://i.pinimg.com/736x/35/dd/dc/35dddca77e508eb8d54effbb2cb48645.jpg",
        trailer: "https://youtu.be/1ovgxN2VWNc?si=opLOURpZrGVPq_fB",
        featured: true,
        latest: false,
        description: "Wabah zombie tiba-tiba menyebar di Korea, dan sekelompok penumpang terjebak di dalam kereta menuju Busan. Di ruang sempit yang penuh kepanikan, mereka harus berjuang bertahan hidup sambil menghadapi ancaman zombie dan sisi egois manusia."
    },
	{
        id: 54,
        type: "movie",
        title: "Parasite",
		genre: "Thriller, Drama",
        actor: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik",
        country: "Korea Selatan",
        year: 2019,
        rating: 8.5,
        poster: "https://i.pinimg.com/1200x/8b/c0/1e/8bc01eb013248cc42cf2f001618d22e2.jpg",
        trailer: "https://youtu.be/isOGD_7hNIY?si=GnxjpI1FS8_3uoyy",
        featured: true,
        latest: false,
        description: "Kisah keluarga miskin yang secara perlahan menyusup ke kehidupan keluarga kaya dengan berbagai cara. Awalnya terlihat cerdik dan menguntungkan, namun situasi berubah menjadi semakin tegang dan tak terduga, mengungkap sisi gelap kesenjangan sosial."
    },
	{
        id: 55,
        type: "movie",
        title: "Exhuma",
		genre: "Horror, Mystery, Thriller",
        actor: "Choi Min-sik, Kim Go-eun, Yoo Hae-jin, Lee Do-hyun",
        country: "Korea Selatan",
        year: 2024,
        rating: 7.2,
        poster: "https://i.pinimg.com/736x/83/94/32/8394322f20b364c261218a3dc7c6feb2.jpg",
        trailer: "https://youtu.be/j_6_wLF1pDg?si=wWPq5yonD3rbW9rh",
        featured: true,
        latest: false,
        description: "Sekelompok ahli feng shui dan paranormal menggali sebuah makam misterius untuk menyelesaikan kasus aneh yang menimpa sebuah keluarga kaya. Namun, tindakan tersebut justru membangkitkan kekuatan gelap yang mengerikan, membawa mereka ke dalam teror yang semakin tak terkendali."
    },
	{
        id: 56,
        type: "movie",
        title: "The Pirates: The Last Royal Treasure",
		genre: "Action, Adventure, Comedy",
        actor: "Kang Ha-neul, Han Hyo-joo",
        country: "Korea Selatan",
        year: 2022,
        rating: 6.1,
        poster: "https://i.pinimg.com/736x/02/a6/25/02a6258cf51fd26755c6cb177424f612.jpg",
        trailer: "https://youtu.be/eSG7Tjx6X9k?si=dT8J7LZw0jyGwWiJ",
        featured: true,
        latest: false,
        description: "Sekelompok bajak laut baru memulai pencarian harta kerajaan yang hilang. Mereka menghadapi petualangan seru di laut dengan tantangan berbahaya dan persaingan antar kelompok."
    },
	{
        id: 57,
        type: "movie",
        title: "20th Century Girl",
		genre: "Romance, Drama",
        actor: "Kim Yoo-jung, Byeon Woo-seok, Park Jung-woo, Roh Yoon-seo",
        country: "Korea Selatan",
        year: 2022,
        rating: 7.3,
        poster: "https://i.pinimg.com/1200x/b2/49/24/b2492404c845e92da1a7fc4600d53bf9.jpg",
        trailer: "https://youtu.be/KFS4_qevE7M?si=NA2SlJvd4LJAK_26",
        featured: true,
        latest: false,
        description: "Berlatar tahun 1999, seorang siswi SMA membantu sahabatnya mendekati pria yang disukai. Namun dalam proses itu, ia justru terlibat dalam kisah cinta pertamanya sendiri yang manis sekaligus menyakitkan, meninggalkan kenangan yang tak terlupakan."
    },
	{
        id: 58,
        type: "movie",
        title: "On Your Wedding Day",
		genre: "Romance, Drama",
        actor: "Park Bo-young, Kim Young-kwang",
        country: "Korea Selatan",
        year: 2018,
        rating: 7.0,
        poster: "https://i.pinimg.com/736x/11/f7/85/11f7852d4dba9ddc1100c02adc43de1b.jpg",
        trailer: "https://youtu.be/QJEe_JEhvw8?si=l2MpgKBhyzY5usdi",
        featured: true,
        latest: false,
        description: "Seorang pria mengenang kisah cinta pertamanya dengan seorang wanita yang ia temui sejak SMA. Hubungan mereka dipenuhi pertemuan dan perpisahan seiring waktu, hingga akhirnya ia menghadiri per"
    },
	{
        id: 59,
        type: "movie",
        title: "Mantis",
		genre: "Action, Crime, Thriller",
        actor: "Jeon Do-yeon, Sul Kyung-gu, Kim Si-a",
        country: "Korea Selatan",
        year: 2025,
        rating: 5.3,
        poster: "https://i.pinimg.com/736x/9a/c7/ec/9ac7ec5c72dfcdcc62ed10c5133803ff.jpg",
        trailer: "https://youtu.be/PItlVyrf15U?si=jvgV-3c_LU9xxgRv",
        featured: true,
        latest: false,
        description: "Seorang assassin elite bernama Mantis hidup di dunia pembunuh bayaran yang terorganisir, di mana ia harus bertahan di tengah persaingan brutal antar pembunuh, pengkhianatan dalam organisasi, dan misi-misi mematikan yang terus mengancam nyawanya, sambil berusaha tetap berada di puncak dunia kriminal yang penuh aturan kejam dan intrik."
    },
	{
        id: 60,
        type: "movie",
        title: "Mission: Impossible",
		season: "S1",
		genre: "Action, Spy, Thriller",
        actor: "Tom Cruise, Ving Rhames, Simon Pegg, Rebecca Ferguson",
        country: "Amerika Serikat",
        year: 1996,
        rating: 7.1,
        poster: "https://i.pinimg.com/1200x/2f/24/50/2f245076dc73916dfde8432bdd4c4dcf.jpg",
        trailer: "https://youtu.be/L8Pbjh4EZRk?si=vO6hq3OHasTE83Pl",
        featured: true,
        latest: false,
        description: "Seorang agen rahasia elit bernama Ethan Hunt menjalankan misi-misi berbahaya yang tampaknya mustahil, di mana ia harus membongkar organisasi kriminal global, menghadapi pengkhianatan dari dalam, serta mengatasi ancaman teknologi dan senjata mematikan, dengan setiap operasi penuh aksi ekstrem, strategi cerdas, dan keputusan cepat yang menentukan keselamatan dunia."
    },
	{
        id: 61,
        type: "movie",
        title: "Ballerina",
		genre: "Action, Crime, Thriller",
		actor: "Jeon Jong-seo, Kim Ji-hoon, Park Yu-rim",
        country: "Korea Selatan",
        year: 2023,
        rating: 6.4,
        poster: "https://i.pinimg.com/1200x/2f/2a/7f/2f2a7f854f56d1a8fdf606d921802df8.jpg",
        trailer: "https://youtu.be/IhXfUTGVEUI?si=6-YM7rrvpgoCfCUa",
        featured: true,
        latest: false,
        description: "Seorang mantan bodyguard bernama Ok-ju berusaha membalas kematian sahabatnya, seorang balerina bernama Min-hee, yang meninggalkan pesan terakhir penuh misteri sebelum meninggal, sehingga ia terjun ke dunia kriminal untuk memburu pelaku di balik tragedi tersebut, menghadapi jaringan kejahatan yang kejam dengan aksi brutal tanpa ampun demi menuntaskan balas dendamnya."
    },
	{
        id: 62,
        type: "movie",
        title: "The Killer",
		genre: "Action, Crime, Thriller",
		actor: "Jang Hyuk, Lee Seo-young, Bruce Khan",
        country: "Korea Selatan",
        year: 2022,
        rating: 6.8,
        poster: "https://i.pinimg.com/1200x/28/96/95/2896953b06152cbde131fec26d436ea5.jpg",
        trailer: "https://youtu.be/aBxr0DyhD3s?si=SJEKhEtZoMN7wD1t",
        featured: true,
        latest: false,
        description: "Seorang mantan pembunuh bayaran yang sudah pensiun terpaksa kembali ke dunia gelap ketika ia harus melindungi seorang gadis yang dipercayakan kepadanya, namun situasi berubah menjadi perburuan mematikan ketika ia menjadi target organisasi kriminal yang dulu ia tinggalkan, sehingga ia harus menggunakan kembali kemampuan lamanya untuk bertahan hidup dan menyelesaikan konflik berdarah yang mengejarnya."
    },
	{
        id: 63,
        type: "movie",
        title: "Taken",
		season: "S1",
		genre: "Action, Crime, Thriller",
		actor: "Liam Neeson, Maggie Grace, Famke Janssen",
        country: "United States",
        year: 2008,
        rating: 7.8,
        poster: "https://i.pinimg.com/736x/f9/6a/fc/f96afcdfc35b768514d78e51e76fbbfa.jpg",
        trailer: "https://youtu.be/XK9zL0ze9O4?si=SDxB5XicEuQoi4Uv",
        featured: true,
        latest: false,
        description: "Seorang mantan agen rahasia CIA bernama Bryan Mills harus menggunakan kembali kemampuan tempurnya ketika putrinya diculik oleh jaringan perdagangan manusia saat sedang berlibur di Eropa, sehingga ia melakukan pengejaran tanpa henti menggunakan keahlian intelijen dan kekuatan fisiknya untuk menemukan dan menyelamatkan putrinya sebelum terlambat, dengan segala cara yang diperlukan."
    },
	{
        id: 64,
        type: "movie",
        title: "Kingsman: The Secret Service",
		genre: "Action, Spy, Comedy, Adventure",
		actor: "Colin Firth, Taron Egerton, Samuel L. Jackson, Michael Caine",
        country: "United States",
        year: 2014,
        rating: 7.7,
        poster: "https://i.pinimg.com/736x/97/03/5d/97035d29b6c7d30b42b8dde211784ead.jpg",
        trailer: "https://youtu.be/m4NCribDx4U?si=eBFbSZQ9N8k8ObSU",
        featured: true,
        latest: false,
        description: "Seorang remaja jalanan bernama Eggsy direkrut ke organisasi mata-mata rahasia bernama Kingsman, di mana ia dilatih menjadi agen elit untuk menghadapi ancaman global dari seorang miliarder jenius yang berencana “membersihkan” umat manusia dengan cara ekstrem, sehingga Eggsy harus membuktikan dirinya sebagai agen sejati dalam misi penuh aksi, teknologi canggih, dan pertarungan bergaya elegan namun brutal."
    },
	{
        id: 65,
        type: "movie",
        title: "Ip Man",
		season: "S1",
		genre: "Action, Biography, Drama, Martial Arts",
		actor: "Donnie Yen, Lynn Hung, Simon Yam",
        country: "China",
        year: 2008,
        rating: 8.0,
        poster: "https://i.pinimg.com/1200x/da/dc/72/dadc724b04ef5438950020b6595bda6d.jpg",
        trailer: "https://youtu.be/RBYbqO_FUA4?si=YegWZn4Bj6-PRyfs",
        featured: true,
        latest: false,
        description: "Film ini menceritakan kisah nyata Ip Man, seorang master Wing Chun yang hidup di Foshan pada masa invasi Jepang, di mana ia harus melindungi keluarganya dan martabat rakyatnya di tengah penindasan, sambil menghadapi tantangan dari tentara Jepang yang menindas serta membuktikan kekuatan dan kehormatan seni bela diri Wing Chun melalui pertarungan yang menentukan hidup dan mati."
    },
	{
        id: 66,
        type: "movie",
        title: "Spider-Man",
		season: "S1",
		genre: "Action, Adventure, Sci-Fi, Superhero",
		actor: "Tobey Maguire, Kirsten Dunst, Willem Dafoe, James Franco",
        country: "United States",
        year: 2002,
        rating: 7.4,
        poster: "https://i.pinimg.com/1200x/4b/85/64/4b8564278c0e1047b9034c6649ef6b1b.jpg",
        trailer: "https://youtu.be/t06RUxPbp_c?si=QZFSyaFOsJ2j4H9t",
        featured: true,
        latest: false,
        description: "Seorang remaja kutu buku bernama Peter Parker mendapatkan kekuatan super setelah digigit laba-laba yang telah dimodifikasi secara genetik, namun setelah kehilangan orang yang sangat ia sayangi, ia belajar bahwa kekuatan besar datang dengan tanggung jawab besar, sehingga ia memutuskan menjadi Spider-Man dan melindungi kota New York dari ancaman Green Goblin yang berbahaya."
    },
	{
        id: 67,
        type: "movie",
        title: "Titanic",
		genre: "Romance, Drama, Disaster",
		actor: "Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates",
        country: "United States",
        year: 1997,
        rating: 7.9,
        poster: "https://i.pinimg.com/1200x/96/9d/6f/969d6feb6a26e17ea33e48635e8dec0e.jpg",
        trailer: "https://youtu.be/CHekzSiZjrY?si=BtQi3WmtDca0n8oV",
        featured: true,
        latest: false,
        description: "Film ini mengisahkan cinta antara Jack, seorang seniman miskin, dan Rose, wanita bangsawan, yang bertemu di kapal Titanic pada pelayaran yang berakhir tragis ketika kapal mewah tersebut menabrak gunung es dan tenggelam, sehingga kisah cinta mereka harus bertahan di tengah bencana besar yang memisahkan status sosial, kehidupan, dan akhirnya takdir mereka."
    },
	{
        id: 68,
        type: "movie",
        title: "Habibie & Ainun",
		genre: "Romance, Biography, Drama",
		actor: "Reza Rahadian, Bunga Citra Lestari",
        country: "Indonesia",
        year: 2012,
        rating: 7.8,
        poster: "https://i.pinimg.com/736x/27/87/57/2787570278a073a43359fb46ae07c644.jpg",
        trailer: "https://youtu.be/rKGvrEWCG3A?si=S66ZRv1PoIczxLuo",
        featured: true,
        latest: false,
        description: "Film ini menceritakan kisah cinta nyata antara B.J. Habibie dan Ainun, mulai dari pertemuan mereka di masa muda hingga perjalanan hidup bersama sebagai pasangan yang saling mendukung, di mana Ainun selalu menjadi pendamping setia Habibie dalam mengejar karier dan cita-cita besarnya, sementara hubungan mereka diuji oleh jarak, tanggung jawab negara, dan wa"
    },
	{
        id: 69,
        type: "movie",
        title: "Dilan 1990",
		genre: "Romance, Drama, Teen",
		actor: "Iqbaal Ramadhan, Vanesha Prescilla",
        country: "Indonesia",
        year: 2018,
        rating: 7.2,
        poster: "https://i.pinimg.com/1200x/92/55/ba/9255bad53e8bcb70054c052d15f349ee.jpg",
        trailer: "https://youtu.be/X_b-wNkz4DU?si=CxQezu4wFkXVCrLE",
        featured: true,
        latest: false,
        description: "Film ini menceritakan kisah cinta remaja antara Milea, siswi pindahan di Bandung, dengan Dilan, seorang siswa SMA yang terkenal keren, unik, dan sedikit nakal, di mana Dilan mencoba mendekati Milea dengan cara-cara romantis yang tidak biasa, sehingga hubungan mereka berkembang di tengah kehidupan sekolah, persahabatan, dan konflik remaja yang hangat sekaligus emosional."
    },
	{
        id: 70,
        type: "movie",
        title: "The Last: Naruto the Movie",
		genre: "Animation, Action, Romance, Adventure",
		actor: "Junko Takeuchi, Nana Mizuki, Jun Fukuyama (Pengisis Suara)",
        country: "Jepang",
        year: 2014,
        rating: 7.6,
        poster: "https://i.pinimg.com/736x/4e/a1/ac/4ea1acc89881df527b36c92a4fa52082.jpg",
        trailer: "https://youtu.be/tA3yE4_t6SY?si=XwepA36QL-0Imekz",
        featured: true,
        latest: false,
        description: "Setelah Perang Dunia Shinobi berakhir, dunia kembali damai namun bulan mulai mendekati bumi akibat rencana ancaman baru dari keturunan Ōtsutsuki, sehingga Naruto bersama timnya harus menghentikan bahaya tersebut sambil menyadari perasaannya terhadap Hinata yang akhirnya berkembang menjadi kisah cinta di tengah misi penyelamatan dunia."
    },
	{
        id: 71,
        type: "movie",
        title: "Minions",
		genre: "Animation, Comedy, Family, Adventure",
		actor: "Sandra Bullock, Jon Hamm, Michael Keaton, Pierre Coffin(Pengisis Suara)",
        country: "United States",
        year: 2015,
        rating: 6.4,
        poster: "https://i.pinimg.com/1200x/23/03/40/23034035885d5fc414489d9dcbb352ae.jpg",
        trailer: "https://youtu.be/ZSdOwt-G49w?si=OqMeKaDDA_gGuoco",
        featured: true,
        latest: false,
        description: "Film ini menceritakan asal-usul para Minions, makhluk kuning lucu yang selalu mencari “boss” terhebat untuk mereka layani, hingga akhirnya mereka melakukan perjalanan panjang dari zaman purba sampai akhirnya bertemu Scarlet Overkill, seorang penjahat super ambisius, yang membawa mereka ke dalam petualangan konyol penuh kekacauan, aksi lucu, dan misi untuk menjadi asisten penjahat paling hebat di dunia."
    },
{
        id: 72,
        type: "movie",
        title: "Tinker Bell",
		genre: "Animation, Fantasy, Comedy, Family",
		actor: "Mae Whitman, Kristin Chenoweth, Lucy Liu, Raven-Symoné(Pengisis Suara)",
        country: "United States",
        year: 2008,
        rating: 6.8,
        poster: "https://i.pinimg.com/1200x/0e/28/fc/0e28fc07e2da9b5492f02bba53ec3e55.jpg",
        trailer: "https://youtu.be/2HMbcoV25ss?si=KS36aPhsSYXPqx45",
        featured: true,
        latest: false,
        description: "Film ini mengikuti Tinker Bell, peri kecil dari Pixie Hollow yang baru menemukan bakatnya sebagai pembuat barang, namun ia merasa tidak puas dengan perannya dan ingin menjadi peri yang lebih “berpetualang”, sehingga ia mencoba mengubah dirinya dengan berbagai cara, tetapi akhirnya belajar bahwa setiap peri memiliki peran penting dalam menjaga keseimbangan dunia peri."
    },
{
        id: 73,
        type: "movie",
        title: "Pengabdi Setan",
		genre: "Horror, Mystery, Supernatural",
		actor: "Tara Basro, Bront Palarae, Ayu Laksmi",
        country: "Indonesia",
        year: 2017,
        rating: 7.2,
        poster: "https://i.pinimg.com/736x/1d/08/d5/1d08d56fc156d4a3e1d1bc5de518e7dd.jpg",
        trailer: "https://youtu.be/0hSptYxWB3E?si=Ec15eNJBbLkbjG8F",
        featured: true,
        latest: false,
        description: "Sebuah keluarga yang baru ditinggal meninggal oleh ibu mereka mulai mengalami kejadian-kejadian aneh dan mengerikan di rumah mereka, hingga terungkap bahwa sang ibu kembali dengan tanda-tanda misterius dan membawa teror yang berkaitan dengan masa lalu kelam serta ritual yang belum selesai, yang akhirnya mengancam keselamatan seluruh anggota keluarga."
    },
{
        id: 74,
        type: "movie",
        title: "KKN di Desa Penari",
		genre: "Horror, Mystery",
		actor: "Tissa Biani, Achmad Megantara, Adinda Thomas, Aghniny Haque",
        country: "Indonesia",
        year: 2022,
        rating: 6.0,
        poster: "https://i.pinimg.com/736x/41/49/ad/4149adea4f63b82db29091250e6e4f9a.jpg",
        trailer: "https://youtu.be/PAMx9m4Z2V4?si=EaOrIi4LRV07YqLo",
        featured: true,
        latest: false,
        description: "Sekelompok mahasiswa yang menjalani program KKN di sebuah desa terpencil mulai mengalami kejadian mistis dan teror mengerikan setelah mereka tanpa sadar melanggar aturan gaib di desa tersebut, yang ternyata berkaitan dengan sosok penari misterius dan kutukan yang menghantui wilayah itu, hingga satu per satu dari mereka terjebak dalam situasi penuh ketakutan dan ancaman kematian."
    },
{
        id: 75,
        type: "movie",
        title: "Danur",
		genre: "Horror, Supernatural",
		actor: "Prilly Latuconsina, Shareefa Daanish, Kinaryosih",
        country: "Indonesia",
        year: 2017,
        rating: 5.8,
        poster: "https://i.pinimg.com/736x/0d/57/5b/0d575b59d6fa8653fa5bb7a52a4eb1a3.jpg",
        trailer: "https://youtu.be/oBGe7mAzb5M?si=Cqh9o_l0tS4juTbX",
        featured: true,
        latest: false,
        description: "Seorang gadis bernama Risa yang sejak kecil memiliki kemampuan melihat makhluk halus menjalin pertemanan dengan beberapa hantu anak-anak dari masa penjajahan Belanda, namun kehidupannya mulai berubah menjadi penuh teror ketika ia semakin terlibat dengan dunia supranatural yang tidak semua makhluknya bersahabat, sehingga ia harus menghadapi kenyataan antara dunia manusia dan dunia arwah yang terus mengikutinya."
    },
{
        id: 76,
        type: "movie",
        title: "Sewu Dino",
		genre: "Horror, Supernatural",
		actor: "Mikha Tambayong, Rio Dewanto, Marthino Lio",
        country: "Indonesia",
        year: 2023,
        rating: 6.5,
        poster: "https://i.pinimg.com/736x/0e/c6/67/0ec667b54d281fcb39488f89816beca4.jpg",
        trailer: "https://youtu.be/12sXNFbQa6I?si=VGxt9vr2R_P0uEr_",
        featured: true,
        latest: false,
        description: "Seorang perempuan muda yang sedang mencari pekerjaan akhirnya bekerja untuk sebuah keluarga kaya, namun ia tanpa sadar terjebak dalam ritual mistis berbahaya bernama “Sewu Dino” yang mengharuskannya merawat seseorang yang terkena kutukan santet selama 1000 hari, sehingga ia harus bertahan hidup di tengah teror gaib dan aturan mengerikan yang tidak boleh dilanggar."
    },
{
        id: 77,
        type: "movie",
        title: "May the Devil Take You",
		genre: "Horror, Thriller, Supernatural",
		actor: "Chelsea Islan, Pevita Pearce, Karina Suwandi, Ray Sahetapy",
        country: "Indonesia",
        year: 2018,
        rating: 6.5,
        poster: "https://i.pinimg.com/1200x/90/30/90/903090c104c6652d0aa36d631b124dfb.jpg",
        trailer: "https://youtu.be/fHObtMkkHSA?si=jjs4Oi1mqU4soXYF",
        featured: true,
        latest: false,
        description: "Seorang wanita bernama Alfie mencoba mengungkap rahasia kelam masa lalu ayahnya yang kaya namun penuh misteri, hingga ia menemukan sebuah rumah tua yang menyimpan kekuatan gelap dan teror supranatural, di mana ia dan keluarganya mulai diteror oleh makhluk iblis yang berhubungan dengan perjanjian masa lalu yang belum selesai, membuat mereka harus berjuang untuk bertahan hidup dari kekuatan jahat tersebut."
    },
    
	
	
    
	
	
	
    
];
